server:
  port: 7005

spring:
  application:
    name: console-server
    index: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    db: console
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.db}?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0 # 0到1之间，1表示全部采样
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  boot:
    admin:
      client:
        url: http://localhost:7751

management:
  endpoints:
    web:
      exposure:
        include:
          enabled: "*"
cache:
  use2L: false
  multi:
    redis:
      defaultExpiration: 60000
      expires:
        consoleCache: 20000
        permissionCache: 20000
    ehcache:
      config: classpath:cache/ehcache.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/

feign:
  hystrix:
    enabled: true

swagger:
  enable: true