eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/
server:
  port: 7771

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  cache:
    ehcache:
      config: classpath:cache/ehcache.xml
    type: ehcache
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0 # 0到1之间，1表示全部采样
feign:
  hystrix:
    enabled: true